# Generated by Django 3.1.12 on 2021-06-06 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0014_auto_20210105_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corptax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'), ('admin_access', 'Can edit tax rates and monitor all taxes')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CorpTaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField()),
                ('date', models.DateField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eveonline.evecorporationinfo')),
            ],
            options={
                'unique_together': {('corp', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CorpTaxOwed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('isk_owed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid', models.BooleanField(default=False)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eveonline.evecorporationinfo')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('corp', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CorpTaxSettings',
            fields=[
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='eveonline.evecorporationinfo')),
                ('taxed_at', models.FloatField(null=True)),
                ('taxed', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
