# Generated by Django 3.1.12 on 2021-06-05 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0014_auto_20210105_1413'),
        ('Corptax', '0002_auto_20210605_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpTaxSettings',
            fields=[
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='eveonline.evecorporationinfo')),
                ('tax_rate', models.FloatField(null=True)),
                ('taxed', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='corptaxowed',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
