# Generated by Django 3.1.12 on 2021-06-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corptax', '0004_auto_20210606_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corptaxsettings',
            old_name='tax_rate',
            new_name='taxed_at',
        ),
    ]
